# Theme for Tmux (generated by omarchy)

# Status bar
set -g status-style "bg={{ background }},fg={{ foreground }}"
set -g status-left "#[fg={{ accent }},bold]  #S "
set -g status-right "#[fg={{ color6 }}]%H:%M"
set -g status-left-length 40
set -g status-right-length 40

# Window status
setw -g window-status-format "#[fg={{ color8 }}] #I:#W "
setw -g window-status-current-format "#[fg={{ background }},bg={{ accent }},bold] #I:#W "

# Pane borders
set -g pane-border-style "fg={{ color8 }}"
set -g pane-active-border-style "fg={{ accent }}"

# Messages
set -g message-style "bg={{ background }},fg={{ color6 }}"

# Clock
set -g clock-mode-colour "{{ accent }}"

# Copy mode
setw -g mode-style "bg={{ selection_background }},fg={{ selection_foreground }}"
