# Gruvbox palette for catppuccin-tmux
set -gq @thm_bg "#282828"
set -gq @thm_fg "#d4be98"
set -gq @thm_rosewater "#d8a657"
set -gq @thm_flamingo "#ea6962"
set -gq @thm_pink "#d3869b"
set -gq @thm_mauve "#d3869b"
set -gq @thm_red "#ea6962"
set -gq @thm_maroon "#ea6962"
set -gq @thm_peach "#e78a4e"
set -gq @thm_yellow "#d8a657"
set -gq @thm_green "#a9b665"
set -gq @thm_teal "#89b482"
set -gq @thm_sky "#7daea3"
set -gq @thm_sapphire "#7daea3"
set -gq @thm_blue "#7daea3"
set -gq @thm_lavender "#d4be98"
set -gq @thm_subtext_1 "#ddc7a1"
set -gq @thm_subtext_0 "#d4be98"
set -gq @thm_overlay_2 "#928374"
set -gq @thm_overlay_1 "#928374"
set -gq @thm_overlay_0 "#7c6f64"
set -gq @thm_surface_2 "#665c54"
set -gq @thm_surface_1 "#504945"
set -gq @thm_surface_0 "#3c3836"
set -gq @thm_mantle "#282828"
set -gq @thm_crust "#1d2021"
