# Everforest palette for catppuccin-tmux
set -gq @thm_bg "#2d353b"
set -gq @thm_fg "#d3c6aa"
set -gq @thm_rosewater "#e69875"
set -gq @thm_flamingo "#e67e80"
set -gq @thm_pink "#d699b6"
set -gq @thm_mauve "#d699b6"
set -gq @thm_red "#e67e80"
set -gq @thm_maroon "#e67e80"
set -gq @thm_peach "#e69875"
set -gq @thm_yellow "#dbbc7f"
set -gq @thm_green "#a7c080"
set -gq @thm_teal "#83c092"
set -gq @thm_sky "#7fbbb3"
set -gq @thm_sapphire "#7fbbb3"
set -gq @thm_blue "#7fbbb3"
set -gq @thm_lavender "#d3c6aa"
set -gq @thm_subtext_1 "#d3c6aa"
set -gq @thm_subtext_0 "#9da9a0"
set -gq @thm_overlay_2 "#859289"
set -gq @thm_overlay_1 "#6e7b72"
set -gq @thm_overlay_0 "#56635f"
set -gq @thm_surface_2 "#56635f"
set -gq @thm_surface_1 "#475258"
set -gq @thm_surface_0 "#3d484d"
set -gq @thm_mantle "#2d353b"
set -gq @thm_crust "#272e33"
