# Nord palette for catppuccin-tmux
set -gq @thm_bg "#2e3440"
set -gq @thm_fg "#d8dee9"
set -gq @thm_rosewater "#d08770"
set -gq @thm_flamingo "#bf616a"
set -gq @thm_pink "#b48ead"
set -gq @thm_mauve "#b48ead"
set -gq @thm_red "#bf616a"
set -gq @thm_maroon "#bf616a"
set -gq @thm_peach "#d08770"
set -gq @thm_yellow "#ebcb8b"
set -gq @thm_green "#a3be8c"
set -gq @thm_teal "#8fbcbb"
set -gq @thm_sky "#88c0d0"
set -gq @thm_sapphire "#81a1c1"
set -gq @thm_blue "#81a1c1"
set -gq @thm_lavender "#5e81ac"
set -gq @thm_subtext_1 "#eceff4"
set -gq @thm_subtext_0 "#e5e9f0"
set -gq @thm_overlay_2 "#4c566a"
set -gq @thm_overlay_1 "#4c566a"
set -gq @thm_overlay_0 "#434c5e"
set -gq @thm_surface_2 "#434c5e"
set -gq @thm_surface_1 "#3b4252"
set -gq @thm_surface_0 "#3b4252"
set -gq @thm_mantle "#2e3440"
set -gq @thm_crust "#242933"
