# Kanagawa palette for catppuccin-tmux
set -gq @thm_bg "#1f1f28"
set -gq @thm_fg "#dcd7ba"
set -gq @thm_rosewater "#d27e99"
set -gq @thm_flamingo "#e82424"
set -gq @thm_pink "#d27e99"
set -gq @thm_mauve "#957fb8"
set -gq @thm_red "#c34043"
set -gq @thm_maroon "#e82424"
set -gq @thm_peach "#ffa066"
set -gq @thm_yellow "#dca561"
set -gq @thm_green "#98bb6c"
set -gq @thm_teal "#7aa89f"
set -gq @thm_sky "#7fb4ca"
set -gq @thm_sapphire "#7e9cd8"
set -gq @thm_blue "#7e9cd8"
set -gq @thm_lavender "#dcd7ba"
set -gq @thm_subtext_1 "#c8c093"
set -gq @thm_subtext_0 "#dcd7ba"
set -gq @thm_overlay_2 "#727169"
set -gq @thm_overlay_1 "#727169"
set -gq @thm_overlay_0 "#54546d"
set -gq @thm_surface_2 "#54546d"
set -gq @thm_surface_1 "#363646"
set -gq @thm_surface_0 "#2a2a37"
set -gq @thm_mantle "#1f1f28"
set -gq @thm_crust "#16161d"
